<a href="https://colab.research.google.com/github/Bharani-a123/ML-JOURNEY/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [ ]:
array = [1,2,3]
a=np.array(array)
print(a)

[1 2 3]


Functions to create numpy


In [ ]:
a=np.zeros((2,3))
print(a)
b=np.ones((2,3))
print(b)
c=np.full((5,5),8)
print(c)
d=np.arange(1,15,1)
print(d)
e=np.linspace(1,50,90)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]
 [8 8 8 8 8]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 1.          1.5505618   2.1011236   2.65168539  3.20224719  3.75280899
  4.30337079  4.85393258  5.40449438  5.95505618  6.50561798  7.05617978
  7.60674157  8.15730337  8.70786517  9.25842697  9.80898876 10.35955056
 10.91011236 11.46067416 12.01123596 12.56179775 13.11235955 13.66292135
 14.21348315 14.76404494 15.31460674 15.86516854 16.41573034 16.96629213
 17.51685393 18.06741573 18.61797753 19.16853933 19.71910112 20.26966292
 20.82022472 21.37078652 21.92134831 22.47191011 23.02247191 23.57303371
 24.12359551 24.6741573  25.2247191  25.7752809  26.3258427  26.87640449
 27.42696629 27.97752809 28.52808989 29.07865169 29.62921348 30.17977528
 30.73033708 31.28089888 31.83146067 32.38202247 32.93258427 33.48314607
 34.03370787 34.58426966 35.13483146 35.68539326 36.23595506 36.78651685
 37.33707865 37.88764045 38.43820225 

In [ ]:
w=np.random.rand(2,2)
print(w)
e=np.random.randint(1,34,4)
print(e)

[[0.00725447 0.19093253]
 [0.07771426 0.01073903]]
[29 14 23  2]


In [ ]:
j=np.eye(7)
print(j)
k=np.diag([22,33,44])
print(k)

[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
[[22  0  0]
 [ 0 33  0]
 [ 0  0 44]]


## **Numpy Indexing**

In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])

10


In [ ]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix[1,2])

6


In [ ]:
cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],

                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[0,2,0])

7


In [ ]:
#acessing particular rows in 3D array
u=cube[:,[1]]
print(u)

[[[ 4  5  6]]

 [[13 14 15]]]


In [ ]:
i=cube[:,[0,2]]
print(i)

[[[ 1  2  3]
  [ 7  8  9]]

 [[10 11 12]
  [16 17 18]]]


**RESHAPING**

In [ ]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
print(array.reshape(4,4))#here (4=row,4=column) for 1d to 2d;

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
print(array.reshape(2,2,4))  #1d to 2d (2= depth,2=row,2=cloumn)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


# **RESIZE**

In [ ]:
"""Difference between Reshape
 and resize or reshape is just temproray while resize is for Permanent
    while reshape will perform only if is is mathematically possible to reshape
    while resize changes permanently and replace extra sizes with zero """

'Difference between Reshape\n and resize or reshape is just temproray while resize is for Permanent\n    while reshape will perform only if is is mathematically possible to reshape \n    while resize changes permanently and replace extra sizes with zero '

In [ ]:
gfg = np.array([1, 2, 3, 4, 5, 6])
gfg.resize(3,4)
print(gfg)

[[1 2 3 4]
 [5 6 0 0]
 [0 0 0 0]]


# **STACKING**

In [7]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])  # 1D Stack 1D gives 2D else like 2D TO 2D gives 3d so on
print(np.stack((a,b),axis=0))

[[1 2 3]
 [4 5 6]]


In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.stack((a,b),axis=1))

[[1 4]
 [2 5]
 [3 6]]


In [11]:
#2 input 3d arrays

m=np.array([[[1,2,3],
            [4,5,6],
            [7,8,9]],

            [[10,11,12],
            [13,14,15],
            [16,17,18]]])

n=np.array([[[51,52,53],
            [54,55,56],
            [57,58,59]],

            [[110,111,112],
            [113,114,115],
            [116,117,118]]])

# stacking
np.stack((m,n),axis=3)


array([[[[  1,  51],
         [  2,  52],
         [  3,  53]],

        [[  4,  54],
         [  5,  55],
         [  6,  56]],

        [[  7,  57],
         [  8,  58],
         [  9,  59]]],


       [[[ 10, 110],
         [ 11, 111],
         [ 12, 112]],

        [[ 13, 113],
         [ 14, 114],
         [ 15, 115]],

        [[ 16, 116],
         [ 17, 117],
         [ 18, 118]]]])